Attempt to reduce the number of ER requests
eiffel-community/etos pull request #237
Opened 2024-05-29 13:18 UTC by t-persson

### Applicable Issues

None

### Description of the Change

ETOS is doing a lot of requests to the event repositories. This is not scalable at all and we need to reduce the amount of queries we are doing and start working on a better solution.

### Alternate Designs

We could go to the final solution right away, but that is quite a ways away and we should try to reduce the queries now.

### Possible Drawbacks

We will be missing some test case information with this change, this is just flavor and not necessary for an ETOS testrun.
There will also be a few logs that may come at weird times such as "waiting for test suite to start" when you can clearly see from the SSE logs that the suite has started. This should be fine in my opinion.

### Sign-off

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

Signed-off-by: Tobias Persson <tobias.persson@axis.com>

2024-05-30 06:01 UTC, t-persson commented on cli/src/etos_client/test_run/test_run.py
> +                events = self.__collect(etos)
Wrong collector

2024-05-30 06:11 UTC, t-persson commented on cli/src/etos_client/test_run/test_run.py
> +                events = self.__collect(etos)
And the logic is not sound

2024-05-31 11:15 UTC, fredjn requested changes

2024-06-05 08:04 UTC, fredjn approved these changes

2024-06-10 07:24 UTC, merged