Environment request: multiple provider jobs in status checks
eiffel-community/etos pull request #330
Opened 2024-12-16 14:28 UTC by andmat900

### Applicable Issues
- https://github.com/eiffel-community/etos/issues/264

### Description of the Change

This change allows multiple environment provider jobs during job status checks in `EnvironmentRequestReconciler`.

### Alternate Designs

### Possible Drawbacks

### Sign-off

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

Signed-off-by: Andrei Matveyeu, andrei.matveyeu@axis.com

2025-01-15 09:18 UTC, t-persson requested changes

2025-01-15 09:18 UTC, t-persson commented on internal/controller/environmentrequest_controller.go
> +			environmentrequest.Status.Conditions = append(environmentrequest.Status.Conditions, condition)
I don't think we want to have multiple of the same condition type added to the status (not even sure if it is allowed by Kubernetes?)

2025-01-15 09:18 UTC, t-persson commented on internal/controller/environmentrequest_controller.go
> +					//return r.Status().Update(ctx, environmentrequest)
Remove

2025-01-15 14:52 UTC, fredjn approved these changes

2025-01-16 08:40 UTC, andmat900 commented on internal/controller/environmentrequest_controller.go
> +			environmentrequest.Status.Conditions = append(environmentrequest.Status.Conditions, condition)
I see what you mean.

Will it be enough to concatenate all result.Description strings to a single condition.Message?

The logic for setting environment request status will be:
- At least one job failed -> environment request failed
- All jobs successful -> environment request done/successful

Or is there a need for a more sophisticated solution?

2025-01-17 09:12 UTC, t-persson commented on internal/controller/environmentrequest_controller.go
> +			environmentrequest.Status.Conditions = append(environmentrequest.Status.Conditions, condition)
I don't think for this case that we can have a more sophisticated solution, especially if we want to show relevant information..

We could try to add more information to `Status.EnvironmentProviders` which right now is `[]corev1.ObjectReference`. Could this be changed to `[]ObjectReferenceWithResult`.

```
type ObjectReferenceWithResult struct {
  corev1.ObjectReference
  result Result
}
```

Then we could show that information on `kubectl describe environmentrequest`. Not sure if it's worth it though

2025-01-17 12:46 UTC, andmat900 commented on internal/controller/environmentrequest_controller.go
> +			environmentrequest.Status.Conditions = append(environmentrequest.Status.Conditions, condition)
Fixed the usage of conditions. Suggesting the simpler solution for now.

2025-01-17 12:46 UTC, andmat900 commented on internal/controller/environmentrequest_controller.go
> +					//return r.Status().Update(ctx, environmentrequest)
Done

2025-01-20 13:45 UTC, t-persson approved these changes

2025-01-24 10:38 UTC, merged