ProviderReconciler: health check scheduling
eiffel-community/etos pull request #332
Opened 2024-12-18 15:32 UTC by andmat900

### Applicable Issues
- https://github.com/eiffel-community/etos/issues/267

### Description of the Change

This change introduces a new scheduling logic for provider health checks. The health checks are scheduled dynamically based on the provider's health check interval setting and the previous health check result.

### Alternate Designs

### Possible Drawbacks

### Sign-off

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

Signed-off-by: Andrei Matveyeu, andrei.matveyeu@axis.com

2025-01-15 09:03 UTC, t-persson commented on internal/controller/provider_controller.go
> +	intervalNoError := time.Duration(provider.Spec.Healthcheck.IntervalSeconds) * time.Second
If status.LastHealthCheckTime is updated to a metav1.Time we can do this to simplify

```
interval := time.Duration(provider.Spec.Healthcheck.IntervalSeconds) * time.Second
var next time.Time
if provider.Status.LastHealthCheckTime != nil {
  next = provider.Status.LastHealthCheckTime.Time.Add(interval)
} else {
  next = provider.ObjectMeta.CreationTimestamp.Time.Add(interval)
  // Or if we want to check on creation: next = provider.ObjectMeta.CreationTimestamp.Time
}
if time.Until(next) > 0 {
  return ctrl.Result{RequeueAfter: time.Until(next)}, nil
}

// Do check

return ctrl.Result{RequeueAfter: now.Add(interval)}, nil
```

2025-01-15 14:58 UTC, fredjn approved these changes

2025-01-16 11:04 UTC, andmat900 commented on internal/controller/provider_controller.go
> +	intervalNoError := time.Duration(provider.Spec.Healthcheck.IntervalSeconds) * time.Second
Done

2025-01-16 11:04 UTC, andmat900 commented on internal/controller/provider_controller.go
> +		return ctrl.Result{RequeueAfter: time.Duration(1) * time.Second}, nil
Return in this block is now removed.

2025-01-17 08:30 UTC, t-persson requested changes

2025-01-17 08:30 UTC, t-persson commented on internal/controller/provider_controller.go
> +	meta.SetStatusCondition(&provider.Status.Conditions, metav1.Condition{Type: StatusAvailable, Status: metav1.ConditionTrue, Reason: "OK", Message: "Provider is up and running"})
Just doing `SetStatusCondition` does nothing, `r.Status().Update(...)` must be called for it to write the status back on the resource.

2025-01-17 08:30 UTC, t-persson commented on internal/controller/provider_controller.go
We should set `LastHealthCheckTime` on the provider resource here at the start, so that we have it set even on failures.

2025-01-17 12:03 UTC, andmat900 commented on internal/controller/provider_controller.go
> +	meta.SetStatusCondition(&provider.Status.Conditions, metav1.Condition{Type: StatusAvailable, Status: metav1.ConditionTrue, Reason: "OK", Message: "Provider is up and running"})
`SetStatusCondition` now placed before `r.Status().Update()`.

2025-01-17 12:04 UTC, andmat900 commented on internal/controller/provider_controller.go
`LastHealthCheckTime` placed in the beginning of the function.

2025-01-20 12:21 UTC, merged