Added a release process for ETOS.
eiffel-community/etos pull request #45
Opened 2020-10-07 11:49 UTC by t-persson

### Applicable Issues

None

### Description of the Change

Add a release process to explain how ETOS is released and what to expect from us.

### Alternate Designs

There are multiple designed, but during discussion with maintainers this was the proposed one.

### Benefits

Easier for us to keep track and users will be happy knowing what happens in the world of ETOS.

### Possible Drawbacks

We must stick to it :)

### Sign-off

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

Signed-off-by: Tobias Persson <tobias.persson@axis.com>

2020-10-08 08:03 UTC, andjoe-axis commented on source/release_process.rst
> +This means that, at worst, users get a 4 week heads up for breaking changes.
Possibly we can add a clarification eg:

"This means that, at worst, users get a 4 week heads up for breaking changes. And by breaking changes, we mean that a developer may have to change something in their code before they can upgrade."

2020-10-12 07:58 UTC, andjoe-axis approved these changes
+1

2020-10-12 13:45 UTC, fredjn requested changes
We should add a link to one of our github milstones as an example

2020-10-12 15:19 UTC, fredjn approved these changes
+1

2020-10-12 15:23 UTC, merged